// Connors RSI: composite of RSI(close), RSI(streak), RSI(ROC).
// Hand-deriving every step over a realistic ~200-bar series is brutal —
// we lean on constant-series invariants and lock in a small known vector
// via numerical regression. See connorsrsi.js header for the StockSharp
// definition (RSI-of-ROC, not the textbook percent-rank).
//
// calcConnorsRSI now returns an object with four separate per-candle
// series: { rsi, updown, rocrsi, crsi } matching StockSharp's complex-
// indicator inner-value enumeration. The composite CRSI line (the average
// of the three inner RSIs) is in `crsi`; the older code used `value` on a
// flat array — these tests use the `crsi` series now.

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');

const { calcConnorsRSI } = require('../../src/chart/indicators/calc/connorsrsi.js');

function makeCandles(closes) {
    return closes.map((c, i) => ({
        time: `t${i}`, open: c, high: c, low: c, close: c, volume: 0,
    }));
}

function approxEq(actual, expected, eps = 1e-9) {
    assert.ok(
        Math.abs(actual - expected) < eps,
        `expected ${expected}, got ${actual} (delta ${Math.abs(actual - expected)})`,
    );
}

describe('calcConnorsRSI', () => {
    it('empty candles → empty series object', () => {
        const r = calcConnorsRSI([], {});
        assert.deepStrictEqual(r.rsi, []);
        assert.deepStrictEqual(r.updown, []);
        assert.deepStrictEqual(r.rocrsi, []);
        assert.deepStrictEqual(r.crsi, []);
    });

    it('candles fewer than warm-up → every CRSI value null', () => {
        // default params: rsiLength=3, streakLength=2, rocLength=100.
        // 50 candles is well below ROC(100) warm-up → all null.
        const closes = [];
        for (let i = 0; i < 50; i++) closes.push(i + 1);
        const r = calcConnorsRSI(makeCandles(closes), {});
        assert.strictEqual(r.crsi.length, 50);
        for (const p of r.crsi) assert.strictEqual(p.value, null);
    });

    it('super-exponential growth → rsiClose, rsiStreak, rsiROC all = 100 → CRSI = 100', () => {
        // We need all three component series to be strictly monotonically
        // increasing to push every RSI to 100. A series where each step
        // grows the ratio faster than the previous does it:
        //   close[i] = i!  (factorial). ROC(k) ratio = close[i]/close[i-k]
        //   strictly increasing, so RSI(ROC) → 100.
        const closes = [];
        let f = 1;
        for (let i = 1; i <= 20; i++) { f *= i; closes.push(f); }
        const r = calcConnorsRSI(makeCandles(closes), {
            rsiLength: 2, streakLength: 2, rocLength: 2,
        });
        for (let i = 19; i >= 6; i--) {
            const v = r.crsi[i].value;
            if (v === null) continue;
            approxEq(v, 100, 1e-6);
            return;
        }
        assert.fail('no formed CRSI value found');
    });

    it('output length matches candles[] and time is passed through', () => {
        const candles = makeCandles([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
        const r = calcConnorsRSI(candles, { rsiLength: 2, streakLength: 2, rocLength: 2 });
        assert.strictEqual(r.crsi.length, candles.length);
        for (let i = 0; i < candles.length; i++) assert.strictEqual(r.crsi[i].time, candles[i].time);
    });

    it('regression: locked-in value on a known vector', () => {
        // Small mixed series + tiny params so we can lock the computed
        // numeric value. If anyone changes the implementation, this
        // catches drift. Generated by running the implementation itself
        // on the vector below; values agree to 1e-9.
        const closes = [10, 11, 10, 11, 10, 11, 10, 11, 10, 11, 12, 13, 12];
        const r = calcConnorsRSI(makeCandles(closes), {
            rsiLength: 2, streakLength: 2, rocLength: 2,
        });
        // Pick the last bar where all 3 components are formed, lock in
        // the numeric result for regression.
        const last = r.crsi[r.crsi.length - 1].value;
        assert.ok(typeof last === 'number' && Number.isFinite(last), 'last value should be finite');
        // The exact value below was captured from a clean implementation
        // run on this exact vector. Within 1e-8.
        approxEq(last, 29.085579149574595, 1e-8);
    });

    it('invalid params → all-null but correct length', () => {
        const r = calcConnorsRSI(makeCandles([1, 2, 3, 4, 5]), { rsiLength: 0 });
        assert.strictEqual(r.crsi.length, 5);
        for (const p of r.crsi) assert.strictEqual(p.value, null);
    });
});
